_name_or_path:
    value: distilbert-base-uncased
_wandb:
    value:
        cli_version: 0.27.0
        e:
            gjq68qszrj9daz95qcybzp34lq0da5bw:
                codePath: /home/bmislol/VSCode/maintainer-copilot/backend/notebooks/01_train_classifier.ipynb
                codePathLocal: 01_train_classifier.ipynb
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "319765794816"
                        used: "295611490304"
                email: ghanemcharbel219@gmail.com
                executable: /home/bmislol/VSCode/maintainer-copilot/backend/.venv/bin/python
                git:
                    commit: 432303ebc0045bf84b491db8c63c23112fc82571
                    remote: git@github.com:bmislol/maintainer-copilot.git
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-aef3b6d4-e940-5517-9356-7d1138a2def0
                host: bmislol-Legion-5-15IAH7H
                memory:
                    total: "16546951168"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.39
                program: /home/bmislol/VSCode/maintainer-copilot/backend/notebooks/01_train_classifier.ipynb
                python: CPython 3.12.3
                root: /home/bmislol/VSCode/maintainer-copilot/backend/notebooks
                startedAt: "2026-05-19T14:07:04.785947Z"
                writerId: gjq68qszrj9daz95qcybzp34lq0da5bw
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "3":
                - 2
                - 7
                - 13
                - 16
                - 19
                - 62
                - 66
            "4": 3.12.3
            "5": 0.27.0
            "6": 5.8.1
            "8":
                - 1
            "9":
                "1": transformers_trainer
            "12": 0.27.0
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
activation:
    value: gelu
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
architectures:
    value:
        - DistilBertForMaskedLM
attention_dropout:
    value: 0.1
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
batch_eval_metrics:
    value: false
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chunk_size_feed_forward:
    value: 0
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_static_graph:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
deepspeed:
    value: null
dim:
    value: 768
disable_tqdm:
    value: false
do_eval:
    value: true
do_predict:
    value: false
do_train:
    value: false
dropout:
    value: 0.1
dtype:
    value: float32
enable_jit_checkpoint:
    value: false
eos_token_id:
    value: null
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: epoch
eval_use_gather_object:
    value: false
fp16:
    value: true
fp16_full_eval:
    value: false
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: true
hidden_dim:
    value: 3072
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": bug
        "1": feature
        "2": docs
        "3": question
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_num_input_tokens_seen:
    value: "no"
initializer_range:
    value: 0.02
is_encoder_decoder:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        bug: 0
        docs: 2
        feature: 1
        question: 3
labels:
    value:
        - bug
        - feature
        - docs
        - question
learning_rate:
    value: 2e-05
length_column_name:
    value: length
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: true
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: null
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 50
logging_strategy:
    value: steps
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 256
max_position_embeddings:
    value: 512
max_steps:
    value: -1
metric_for_best_model:
    value: macro_f1
model:
    value: distilbert-base-uncased
model/num_parameters:
    value: 66956548
model_type:
    value: distilbert
n_heads:
    value: 12
n_layers:
    value: 6
neftune_noise_alpha:
    value: null
num_train_epochs:
    value: 4
optim:
    value: adamw_torch_fused
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ../data/classifier_artifacts/checkpoints
output_hidden_states:
    value: false
pad_token_id:
    value: 0
parallelism_config:
    value: null
per_device_eval_batch_size:
    value: 32
per_device_train_batch_size:
    value: 16
prediction_loss_only:
    value: false
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
qa_dropout:
    value: 0.1
remove_unused_columns:
    value: true
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
run_name:
    value: null
save_on_each_node:
    value: false
save_only_model:
    value: false
save_steps:
    value: 500
save_strategy:
    value: epoch
save_total_limit:
    value: 2
seed:
    value: 42
seq_classif_dropout:
    value: 0.2
sinusoidal_pos_embds:
    value: false
skip_memory_metrics:
    value: true
test_size:
    value: 578
tf32:
    value: null
tie_weights_:
    value: true
tie_word_embeddings:
    value: true
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
trackio_bucket_id:
    value: null
trackio_space_id:
    value: null
trackio_static_space_id:
    value: null
train_sampling_strategy:
    value: random
train_size:
    value: 2690
transformers_version:
    value: 5.8.1
use_cache:
    value: false
use_cpu:
    value: false
use_liger_kernel:
    value: false
val_size:
    value: 576
vocab_size:
    value: 30522
warmup_ratio:
    value: 0.1
warmup_steps:
    value: 0.1
weight_decay:
    value: 0.01
