_wandb:
    value:
        cli_version: 0.27.0
        e:
            56quofmann7v9o0v1a6evcczlutpjh46:
                codePath: /home/bmislol/VSCode/maintainer-copilot/backend/notebooks/01_train_classifier.ipynb
                codePathLocal: 01_train_classifier.ipynb
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "319765794816"
                        used: "293749047296"
                email: ghanemcharbel219@gmail.com
                executable: /home/bmislol/VSCode/maintainer-copilot/backend/.venv/bin/python
                git:
                    commit: 432303ebc0045bf84b491db8c63c23112fc82571
                    remote: git@github.com:bmislol/maintainer-copilot.git
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-aef3b6d4-e940-5517-9356-7d1138a2def0
                host: bmislol-Legion-5-15IAH7H
                memory:
                    total: "16546951168"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.39
                program: /home/bmislol/VSCode/maintainer-copilot/backend/notebooks/01_train_classifier.ipynb
                python: CPython 3.12.3
                root: /home/bmislol/VSCode/maintainer-copilot/backend/notebooks
                startedAt: "2026-05-19T13:39:58.862568Z"
                writerId: 56quofmann7v9o0v1a6evcczlutpjh46
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.27.0
            "6": 5.8.1
            "8":
                - 1
            "12": 0.27.0
            "13": linux-x86_64
labels:
    value:
        - bug
        - feature
        - docs
        - question
max_length:
    value: 256
model:
    value: distilbert-base-uncased
seed:
    value: 42
test_size:
    value: 578
train_size:
    value: 2690
val_size:
    value: 576
